### ISSUE TITLE
Import Wireguard + StaticIP configurations 

### ISSUE THREAD

**Issue by brh28** [AndySchroder/StaticWire#2]
I originally purchased my staticIP from within a docker container. From within this container, I was able to run the StaticIP commands (e.g `GetConf`) successfully. However, after restarting the container, it appears I have a new key-pair set up, so I'm no longer able to use the StaticIP commands as before. Fortunately, I did copy the Wireguard conf file to my host, so I'm still able to connect to my VPN, but it would be nice to have an import function for container services.

**Comment by AndySchroder** [comment]
Did you restart or rebuild the container?

**Comment by brh28** [comment]
yes

**Comment by AndySchroder** [comment]
The `staticIP` command writes its config to `$HOME/.StaticWire/Config.yaml`. Inside the container that should be `/root/.StaticWire/Config.yaml`. You can copy and paste the value of `PrivateKey = ` from the `[Interface]` section of the wireguard .conf file into the `private_key: ` section of `Config.yaml`. Also, you can generate your public key using your private key using `$ echo "privatekey"|wg pubkey`, and then paste the result into the `public_key: ` section of `Config.yaml`. That should restore  `Config.yaml` for you.

**Comment by AndySchroder** [comment]
> yes

Yes to restart or Yes to rebuild?

**Comment by brh28** [comment]
Ah, rebuild. But I also tried the `docker compose up` without the --build flag and had the same issue.

Perfect, updating the `/root/.StaticWire/Config.yaml` with your instructions worked. It might be nice to add that logic to the CLI so clean deploys.

**Comment by AndySchroder** [comment]
Did you make any changes to `docker-compose.yml` before running `docker compose up`? If so, that might have forced a rebuild.

Agreed, adding some notes to the README file about how to rebuild `Config.yaml` from a wireguard .conf file would be useful.
